// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetError() {
  return window['go']['main']['App']['GetError']();
}

export function SetBrightness(arg1, arg2) {
  return window['go']['main']['App']['SetBrightness'](arg1, arg2);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function TurnOff(arg1) {
  return window['go']['main']['App']['TurnOff'](arg1);
}

export function TurnOn(arg1) {
  return window['go']['main']['App']['TurnOn'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
